### ISSUE TITLE
`data.json` have duplicate image source

### ISSUE THREAD

**Issue by siddhantprateek** [siddhantprateek/rteach#5]
replace the source of Debajoty Banik with `https://cse.kiit.ac.in/wp-content/uploads/2020/06/Debajyoty-Banik.jpg`

**Desired State**
```
{
   Name: "Debajoty Banik",
   source: "https://cse.kiit.ac.in/wp-content/uploads/2020/06/Debajyoty-Banik.jpg"
}
```

**Comment by RishiKumarRay** [comment]
I would like to do this , can you let me know where it is in the code?

**Comment by siddhantprateek** [comment]
@RishiKumarRay, I'm sorry I guess, I have to close this issue, React was having some rendering issues so, it was having duplicate images. but you can still check the file if there are no duplicates in it and report an issue.
```
├───client
│   ├───public
│   └───src
│       ├───assets 👈
│       ├───components
│       │   ├───header
│       │   ├───teacher-list
│       │   └───teacher-profile
│       └───routes
│           ├───dashboard
│           ├───home
│           └───profile
└───server
```
